x-db-env: &db-env
  DB_USER: postgres
  DB_PASSWORD: postgres
  DB_HOST: postgres
  DB_PORT: 5432
  DB_NAME: hh_bot

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "127.0.0.1:6379:6379"

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: hh_bot
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  alembic:
    build:
      context: .
      dockerfile: ./alembic/Dockerfile
    container_name: alembic
    command: upgrade head
    volumes:
      - ./db:/app/db
      - ./alembic:/app/alembic
      - ./alembic.ini:/app/alembic.ini
    environment:
      <<: *db-env
    depends_on:
      - postgres

  hh-service:
    build:
      context: .
      dockerfile: ./hh_service/Dockerfile
    container_name: hh-service
    volumes:
      - ./db:/app/db
      - ./hh_service:/app/hh_service
    ports:
      - "127.0.0.1:8000:8000"
    environment:
      <<: *db-env
      API_HOST: 0.0.0.0
      API_PORT: 8000
    depends_on:
      - postgres
      - alembic

  scheduler-api:
    build:
      context: .
      dockerfile: ./scheduler/Dockerfile
    container_name: scheduler-api
    volumes:
      - ./db:/app/db
      - ./scheduler:/app/scheduler
      - ./fabric:/app/fabric
    ports:
      - "127.0.0.1:8002:8002"
    environment:
      <<: *db-env
      API_HOST: 0.0.0.0
      API_PORT: 8002
      REDIS_HOST: redis
      REDIS_PORT: 6379
    command: python api/main.py
    depends_on:
      - redis
      - hh-service

  scheduler-worker:
    build:
      context: .
      dockerfile: ./scheduler/Dockerfile
    container_name: scheduler-worker
    volumes:
      - ./db:/app/db
      - ./scheduler:/app/scheduler
      - ./fabric:/app/fabric
    environment:
      <<: *db-env
      REDIS_HOST: redis
      REDIS_PORT: 6379
    command: celery -A scheduler.tasks worker --loglevel=info
    depends_on:
      - redis
      - hh-service

  scheduler-beat:
    build:
      context: .
      dockerfile: ./scheduler/Dockerfile
    container_name: scheduler-beat
    volumes:
      - ./db:/app/db
      - ./scheduler:/app/scheduler
      - ./fabric:/app/fabric
    environment:
      <<: *db-env
      REDIS_HOST: redis
      REDIS_PORT: 6379
    command: celery -A scheduler.tasks beat --scheduler redbeat.RedBeatScheduler --loglevel=info
    depends_on:
      - redis
      - hh-service

  admin-panel:
    build:
      context: .
      dockerfile: ./admin_panel/Dockerfile
    container_name: admin-panel
    volumes:
      - ./db:/app/db
      - ./admin_panel:/app/admin_panel
      - ./fabric:/app/fabric
    ports:
      - "127.0.0.1:8001:8001"
    environment:
      <<: *db-env
      API_HOST: 0.0.0.0
      API_PORT: 8001
    depends_on:
      - postgres
      - alembic

volumes:
  pgdata: