x-db-env: &db-env
  DB_USER: postgres
  DB_PASSWORD: postgres
  DB_HOST: postgres
  DB_PORT: 5432
  DB_NAME: hh_bot

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "127.0.0.1:6379:6379"

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: hh_bot
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -h localhost" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s

  alembic:
    build:
      context: .
      dockerfile: ./alembic/Dockerfile
    container_name: alembic
    command: upgrade head
    volumes:
      - ./db:/app/db
      - ./alembic:/app/alembic
      - ./alembic.ini:/app/alembic.ini
    environment:
      <<: *db-env
    depends_on:
      postgres:
        condition: service_healthy
        restart: true

  hh-service:
    build:
      context: .
      dockerfile: ./hh_service/Dockerfile
    container_name: hh-service
    volumes:
      - ./db:/app/db
      - ./hh_service:/app/hh_service
    ports:
      - "127.0.0.1:8000:8000"
    environment:
      <<: *db-env
      API_HOST: 0.0.0.0
      API_PORT: 8000
      SECRET_KEY: secret-string
      SESSION_MAX_AGE: 1209600
      CLIENT_ID: YOUR_CLIENT_ID
      CLIENT_SECRET: YOUR_CLIENT_SECRET
    depends_on:
      postgres:
        condition: service_healthy
        restart: true
      alembic:
        condition: service_completed_successfully

  scheduler-api:
    build:
      context: .
      dockerfile: ./scheduler/Dockerfile
    container_name: scheduler-api
    volumes:
      - ./db:/app/db
      - ./scheduler:/app/scheduler
      - ./fabric:/app/fabric
    ports:
      - "127.0.0.1:8002:8002"
    environment:
      <<: *db-env
      API_HOST: 0.0.0.0
      API_PORT: 8002
      REDIS_HOST: redis
      REDIS_PORT: 6379
    command: python api/main.py
    depends_on:
      redis:
        condition: service_started
      hh-service:
        condition: service_started

  scheduler-worker:
    build:
      context: .
      dockerfile: ./scheduler/Dockerfile
    container_name: scheduler-worker
    volumes:
      - ./db:/app/db
      - ./scheduler:/app/scheduler
      - ./fabric:/app/fabric
    environment:
      <<: *db-env
      REDIS_HOST: redis
      REDIS_PORT: 6379
    command: celery -A scheduler.tasks worker --loglevel=info
    depends_on:
      redis:
        condition: service_started
      hh-service:
        condition: service_started

  scheduler-beat:
    build:
      context: .
      dockerfile: ./scheduler/Dockerfile
    container_name: scheduler-beat
    volumes:
      - ./db:/app/db
      - ./scheduler:/app/scheduler
      - ./fabric:/app/fabric
    environment:
      <<: *db-env
      REDIS_HOST: redis
      REDIS_PORT: 6379
      BEAT_MAX_LOOP_INTERVAL: 5
    command: celery -A scheduler.tasks beat --scheduler redbeat.RedBeatScheduler --loglevel=info
    depends_on:
      redis:
        condition: service_started
      hh-service:
        condition: service_started

  admin-panel:
    build:
      context: .
      dockerfile: ./admin_panel/Dockerfile
    container_name: admin-panel
    volumes:
      - ./db:/app/db
      - ./admin_panel:/app/admin_panel
      - ./fabric:/app/fabric
    ports:
      - "127.0.0.1:8001:8001"
    environment:
      <<: *db-env
      API_HOST: 0.0.0.0
      API_PORT: 8001
    depends_on:
      postgres:
        condition: service_healthy
        restart: true
      alembic:
        condition: service_completed_successfully

  nginx:
    image: nginx:alpine
    container_name: hh-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - hh-service

volumes:
  pgdata: