version: '3.9'

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "127.0.0.1:6379:6379"

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: hh_bot
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  hh-service:
    image: hh-service:latest
    container_name: hh-service
    volumes:
      - ./shared_utils:/app/shared_utils
      - ./db:/app/db
      - ./hh_service:/app/hh_service
    ports:
      - "127.0.0.1:8000:8000"
    environment:
      API_HOST: 0.0.0.0
      API_PORT: 8000
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: hh_bot
    depends_on:
      - postgres

  scheduler:
    image: scheduler:latest
    container_name: scheduler
    volumes:
      - ./shared_utils:/app/shared_utils
      - ./db:/app/db
      - ./scheduler:/app/scheduler
    environment:
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: hh_bot
    depends_on:
      - redis
      - hh-service
      - postgres

  admin-panel:
    image: admin-panel:latest
    container_name: admin-panel
    volumes:
      - ./shared_utils:/app/shared_utils
      - ./db:/app/db
      - ./admin_panel:/app/admin_panel
      - ./fabric:/app/fabric
    ports:
      - "127.0.0.1:8001:8001"
    environment:
      API_HOST: 0.0.0.0
      API_PORT: 8001
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: hh_bot
    depends_on:
      - postgres

volumes:
  pgdata:
