"""add cron_schedule

Revision ID: 03e0b4cf5fdd
Revises: b6588ab56140
Create Date: 2025-06-30 18:22:58.433533

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

import db

# revision identifiers, used by Alembic.
revision: str = "03e0b4cf5fdd"
down_revision: Union[str, Sequence[str], None] = "b6588ab56140"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "auto_apply_config",
        sa.Column(
            "cron_schedule", db.models.base.CronSchedule(), nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("auto_apply_config", "cron_schedule")
    # ### end Alembic commands ###
