"""add_message

Revision ID: 0c396fdc8313
Revises: 03e0b4cf5fdd
Create Date: 2025-07-14 15:41:38.629652

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0c396fdc8313"
down_revision: Union[str, Sequence[str], None] = "03e0b4cf5fdd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "auto_apply_config", sa.Column("message", sa.String(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("auto_apply_config", "message")
    # ### end Alembic commands ###
