"""add telegram_id

Revision ID: 30c30bdc54b0
Revises: bfbf036d7c9b
Create Date: 2025-07-31 14:24:38.064647

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "30c30bdc54b0"
down_revision: Union[str, Sequence[str], None] = "bfbf036d7c9b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "session", sa.Column("telegram_id", sa.Integer(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("session", "telegram_id")
    # ### end Alembic commands ###
