"""add saved searches

Revision ID: 87ce3b75e885
Revises: 30c30bdc54b0
Create Date: 2025-08-14 21:24:41.071008

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "87ce3b75e885"
down_revision: Union[str, Sequence[str], None] = "30c30bdc54b0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "auto_apply_config",
        sa.Column("saved_search_id", sa.String(), nullable=True),
    )
    op.alter_column(
        "auto_apply_config",
        "filter_id",
        existing_type=sa.INTEGER(),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "auto_apply_config",
        "filter_id",
        existing_type=sa.INTEGER(),
        nullable=False,
    )
    op.drop_column("auto_apply_config", "saved_search_id")
    # ### end Alembic commands ###
