"""merge

Revision ID: bfbf036d7c9b
Revises:
Create Date: 2025-07-24 23:29:33.035734

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

import db

# revision identifiers, used by Alembic.
revision: str = "bfbf036d7c9b"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "client",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "filter",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "query", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "session",
        sa.Column("id", db.models.base.UUIDString(), nullable=False),
        sa.Column("client_id", sa.String(), nullable=False),
        sa.Column(
            "token", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("state", db.models.base.UUIDString(), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("encoded", sa.String(), nullable=True),
        sa.Column("mode", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["client_id"], ["client.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("state"),
    )
    op.create_table(
        "auto_apply_config",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("client_id", sa.String(), nullable=False),
        sa.Column("resume_id", sa.String(), nullable=False),
        sa.Column("session_id", sa.UUID(), nullable=False),
        sa.Column("filter_id", sa.Integer(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("max_applications", sa.Integer(), nullable=False),
        sa.Column("similar_vacancies", sa.Boolean(), nullable=False),
        sa.Column(
            "cron_schedule", db.models.base.CronSchedule(), nullable=False
        ),
        sa.Column("message", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["client_id"], ["client.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["filter_id"], ["filter.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["session_id"], ["session.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("auto_apply_config")
    op.drop_table("session")
    op.drop_table("filter")
    op.drop_table("client")
    # ### end Alembic commands ###
